# Generated by Django 4.2.7 on 2024-02-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Наименование рассылки')),
                ('time_start', models.DateTimeField(verbose_name='Время начала')),
                ('time_stop', models.DateTimeField(verbose_name='Время окончания')),
                ('frequency', models.CharField(choices=[('HOUR', 'раз в час'), ('WEEK', 'раз в неделю'), ('MONTH', 'раз в месяц')], default='WEEK', max_length=5, verbose_name='Периодичность рассылки')),
                ('status_mailing', models.CharField(choices=[('COMPLETED', 'завершена'), ('CREATED', 'создана'), ('LAUNCHED', 'запущена')], default='COMPLETED', max_length=10, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('message', models.TextField(verbose_name='Тело письма')),
                ('message_for_mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Сообщение рассылки')),
            ],
        ),
    ]
