# Generated by Django 4.2.7 on 2024-02-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='user',
            new_name='user_creator',
        ),
    ]
