# Generated by Django 4.2.7 on 2024-02-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_message_options_alter_mailing_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('HOUR', 'раз в час'), ('WEEK', 'раз в неделю'), ('MONTH', 'раз в месяц')], default='WEEK', max_length=12, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status_mailing',
            field=models.CharField(choices=[('COMPLETED', 'завершена'), ('CREATED', 'создана'), ('LAUNCHED', 'запущена')], default='COMPLETED', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
