# Generated by Django 4.2.7 on 2024-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя клиента')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия клиента')),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий клиента')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
