# Generated by Django 4.2.7 on 2024-02-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': (('blog_custom_perm', 'модератор блога'),), 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
